version: 1.0.{build}
branches:
  only:
  - master
before_build:
- ps: nuget restore ./Parser/Parser.sln
build:
  project: ./Parser/Parser.sln
  verbosity: minimal
notifications:
- provider: Email
  to:
  - todorov.h@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true

environment:
  COVERALLS_REPO_TOKEN:
    secure: DOk9i0IebrlcZDodTNY5nEUZ3v9KOWz8MAQabAzo8PTavkDf33l3EQfuxmx2tVkb

after_test: 
  - Parser\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"Parser\packages\NUnit.ConsoleRunner.3.6.0\tools\nunit3-console.exe" -targetargs:"/domain:single  Parser\Tests\Parser.LogFileReader.Tests\bin\Debug\Parser.LogFileReader.Tests.dll Parser\Tests\Parser.SignalR.Tests\bin\Debug\Parser.SignalR.Tests.dll Parser\Tests\Parser.Common.Tests\bin\Debug\Parser.Common.Tests.dll Parser\Tests\Parser.LogFileParser.Tests\bin\Debug\Parser.LogFileParser.Tests.dll Parser\Tests\Parser.Data.Services.Tests\bin\Debug\Parser.Data.Services.Tests.dll Parser\Tests\Parser.Data.Tests\bin\Debug\Parser.Data.Tests.dll" -output:coverage.xml

  - Parser\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml