version: 1.0.{build}
branches:
  only:
  - master
before_build:
- ps: nuget restore ./Parser/Parser.sln
build:
  project: ./Parser/Parser.sln
  verbosity: minimal
notifications:
- provider: Email
  to:
  - todorov.h@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true

# environment:
#   COVERALLS_REPO_TOKEN:
#     secure: Iy19m2KbHWZ5DxgCNCuCJtjUeW06RBJBNu026eiyHaap4zy36rgA1mbwh4m/guKq

# after_test: 
#   - Parser\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"WhenItsDone\packages\NUnit.ConsoleRunner.3.6.0\tools\nunit3-console.exe" -targetargs:"/domain:single  WhenItsDone\Tests\LibTests\WhenItsDone.Models.Tests\bin\Debug\WhenItsDone.Models.Tests.dll WhenItsDone\Tests\LibTests\WhenItsDone.Services.Tests\bin\Debug\WhenItsDone.Services.Tests.dll WhenItsDone\Tests\LibTests\WhenItsDone.Data.Tests\bin\Debug\WhenItsDone.Data.Tests.dll" -output:coverage.xml

#   - Parser\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml